### ISSUE TITLE
Doesn't work on Android 8 

### ISSUE THREAD

**Issue by Grind3x** [vladfux4/DS4Adapter#1]
Hi. I tried install it on Android 8 via Xposed and got an error: "Download file is not valid APK(or incompartible)".

Should it work on Android 8?

**Comment by vladfux4** [comment]
Hi Vitalii,
Actually there is no dependencies from Android 9, for witch apk was build. 
Android SDK was downgraded to version 8.0 (26)
Please, try with latest version of module from repo.xposed (1.02)
Your feedback is welcome

**Comment by max8938** [comment]
Hi, is it possible to downgrade the SDK even more, to 6.0?

**Comment by Grind3x** [comment]
Thank you. Now all is good. Stable works on Android 8.0 with 1controller Magisk module.
